name: 'hv_edp_dbt'
version: '1.0.0'

require-dbt-version: ">=1.10.0,<1.11.0"

profile: 'hv_edp_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

vars:
  stage_location: ""
  filtered_fund_ids: []
  filtered_fund_ids: []

models:
  hv_edp_dbt:
    bronze:
      +schema: "bronze"
      +meta:
        dagster:
          group:
            "bronze"
      deltas:
        +materialized: incremental
      full_snapshots:
        +materialized: table
    silver:
      +schema: "silver"
      +materialized: table
      +meta:
        dagster:
          group:
            "silver"
    gold:
      +schema: "gold"
      +materialized: table
      +meta:
        dagster:
          group:
            "gold"
      