version: 2

sources:
    - name: bronze_from_harborview_edw
      description: Raw data uploaded from CSVs.
      database: "{{ target.database }}"
      schema: "{{ env_var('ENVIRONMENT') }}_BRONZE"
      meta:
        source_db: HARBOURVIEW_EDW
        source_file_format: CSV
      tables:
          - name: dim_fund
            description: DIM_FUND loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_fund']
          - name: fact_investor_transactions
            description: FACT_INVESTOR_TRANSACTIONS loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_investor_transactions']
          - name: currency
            description: CURRENCY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_currency']
          - name: global_edw_key_to_iqid
            description: GLOBAL_EDW_KEY_TO_IQID loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_global_edw_key_to_iqid']
          - name: dim_fund_sub_perspective
            description: DIM_FUND_SUB_PERSPECTIVE loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_fund_sub_perspective']
          - name: dim_portfolios
            description: DIM_PORTFOLIOS loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_portfolios']
          - name: fact_investment_transactions_fund_hierarchy_monthly
            description: FACT_INVESTMENT_TRANSACTIONS_FUND_HIERARCHY_MONTHLY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_investment_transactions_fund_hierarchy_monthly']
          - name: fact_investment_transactions_fund_hierarchy
            description: FACT_INVESTMENT_TRANSACTIONS_FUND_HIERARCHY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_investment_transactions_fund_hierarchy']
          - name: dim_fund_hierarchy
            description: DIM_FUND_HIERARCY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_fund_hierarchy']
          - name: fact_investor_transactions_fund_hierarchy
            description: FACT_INVESTOR_TRANSACTIONS_FUND_HIERARCHY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_investor_transactions_fund_hierarchy']
          - name: dim_type_broad
            description: DIM_TYPE_BROAD loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_type_broad']
          - name: dim_hv_geography_hierarchy
            description: DIM_HV_GEOGRAPHY_HIERARCHY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_hv_geography_hierarchy']
          - name: dim_company_industry_hierarchy
            description: DIM_COMPANY_INDUSTRY_HIERARCHY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_company_industry_hierarchy']
          - name: dim_manager
            description: DIM_MANAGER loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_manager']
          - name: stage
            description: STAGE loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_stage']
          - name: fact_irr_investor
            description: FACT_IRR_INVESTOR loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_irr_investor']
          - name: calendar
            description: CALENDAR loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_calendar']
          - name: calendar_quarter
            description: CALENDAR_QUARTER loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_calendar_quarter']
          - name: calendar_month
            description: CALENDAR_MONTH loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_calendar_month']
          - name: fact_fund_sub_perspective_funds
            description: FACT_FUND_SUB_PERSPECTIVE_FUNDS loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_fund_sub_perspective_funds']
          - name: fact_irr_investment_fund_hierarchy
            description: FACT_IRR_INVESTMENT_FUND_HIERARCHY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_irr_investment_fund_hierarchy']
