version: 2

sources:
    - name: hv_source
      description: Raw data uploaded from CSVs.
      database: "{{ target.database }}"
      schema: "{{ env_var('ENVIRONMENT') }}_BRONZE"
      tables:
          - name: dim_fund
            description: DIM_FUND loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_fund']
          - name: fact_investor_transactions
            description: FACT_INVESTOR_TRANSACTIONS loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_investor_transactions']
          - name: currency
            description: CURRENCY loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_currency']
          - name: global_edw_key_to_iqid
            description: GLOBAL_EDW_KEY_TO_IQID loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_global_edw_key_to_iqid']
          - name: dim_fund_sub_perspective
            description: DIM_FUND_SUB_PERSPECTIVE loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_dim_fund_sub_perspective']
