version: 2

sources:
    - name: hv_source
      description: Raw data uploaded from CSVs.
      database: "{{ target.database }}"
      schema: "{{ env_var('ENVIRONMENT') }}_BRONZE"
      tables:
          - name: dim_fund
            description: dim funds data.
            meta:
              dagster:
                asset_key: ['bronze_dim_fund']
                group: "DIM_FUND"