version: 2

sources:
    - name: hv_source
      description: Raw data uploaded from CSVs.
      database: "{{ target.database }}"
      schema: "{{ env_var('ENVIRONMENT') }}_BRONZE"
      tables:
          - name: dim_fund
            description: dim funds data.
            meta:
              dagster:
                asset_key: ['bronze_dim_fund']
                group: "BRONZE"
          - name: fact_investor_transactions
            description: FACT_INVESTOR_TRANSACTIONS loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_fact_investor_transactions']
                group: "BRONZE"
          - name: fact_investor_transactions
            description: FACT_INVESTOR_TRANSACTIONS loaded from Harbourview EDW
            meta:
              dagster:
                asset_key: ['bronze_currency']
                group: "BRONZE"